### ISSUE TITLE
[Bug]: Gendered Intelligence is assigned to an out of date neighbourhood

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2110]
## Description

GI is giving a notification that the neighbourhood it's in is out of date.

## Steps to reproduce

1. Go here: https://admin.placecal.org/partners/gendered-intelligence/edit

"The address for this partner is assigned to an out of date neighbourhood. You do not need to take any action but if you wish to reassign this to an up to date neighbourhood please contact support at [support@placecal.org](mailto:support@placecal.org)."

## What you expected to happen

It not to say this - unclear why it's happening but wanted to flag. Perhaps not a bug.

**Comment by katjam** [comment]
Should have been fixed by Neighbourhood update.

**Comment by kimadactyl** [comment]
> Should have been fixed by Neighbourhood update.

But its not and the error is still visible

<img width="656" alt="Screenshot 2024-04-08 at 16 47 16" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/c79f7714-a129-48e6-bf30-c449472fbdbf">

**Comment by kimadactyl** [comment]
Maybe all that needs to happen is to clear the address and re-save? Would that fix it and if so do we need to document that somewhere as what to do if this error pops up?

**Comment by katjam** [comment]
Also double checking @geeksforsocialchange/developers did we try to verify this too soon? As in, has the address update happened on production yet or happening after release?

**Comment by r-ferrier** [comment]
closing so we can reverify this as part of 29

**Comment by ivan-kocienski-gfsc** [comment]
This looks like it is still broken, also the "clear address" button seems to not work

**Comment by aaaaargZombies** [comment]
## verified

just needed to change the address then re-add it back in to update to the new dataset

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/ea0351bd-99af-49dd-aec4-2c6e5a461752)
